### ISSUE TITLE
Avoid Adding the same track to the audioProvider

### ISSUE THREAD

**Issue by ehusaint** [arielfaur/ionic-audio#109]
I have multiple album within this app. As I navigate within each album, when I call the function to get all track by using the "audioProvider.tracks", i have the same tracks been added to the list. How can I avoid that. Here is the example:

1. Navigate to album A
2. 3 tracks are listed and are added to audioProviders - All tracks is equals to 3 item in array. 
3. Go back. 
4. Navigate to Album A again. 
5. 3 tracks are listed and are added again to the audioProviders - All tracks is equal to 6 items in the array. 

How do I avoid audioProvider to add the same three tracks to the list?

I'm using ionic-audio 2.

**Comment by ehusaint** [comment]
Anyone please?

**Comment by ehusaint** [comment]
@arielfaur - Thanks for responding. Is there a way currently to clear all the tracks within audioProvider?

**Comment by arielfaur** [comment]
@ehusaint I think this may be related to the way you are creating the bindings. The module will simply bind to an array of tracks. Maybe you should change the place where the binding takes place. For example use the constructor or any of the Angular or Ionic page cycle events to make sure that happens only once.

**Comment by ehusaint** [comment]
@arielfaur - I could be wrong here but I feel like the binding is happening on load of a page. I'm using your <audio-track> component. That component loads the audio every time the page is loaded. I'm not loading the tracks manually. Am I missing something?

**Comment by arielfaur** [comment]
Can you show me the code of your page component?

**Comment by ehusaint** [comment]
@arielfaur - It's a same code that is in your demo example. So here is the setup i have. There is a home page with album names. Click on album page and it goes to album listing. Once i click play on one of the song within the album, and i navigate back to the home page and come back to the same album page, the id's of all the track on the album page has changed. Because every time I navigate to album page, it creates different ids for the same track. So there is no way to know if this particular track is currently playing or not? Here is the code on the album page. 

```
 <audio-track #audio *ngFor="let track of albumDetails" [track]="track" (onFinish)="onTrackFinished($event)">
      <ion-item>
        <audio-track-play  [audioTrack]="audio" item-left>
            <ion-spinner></ion-spinner>
          </audio-track-play>
       
        <div item-content style="width:100%" padding-right>
          <small>{{audio.title}}
          </small>
          <audio-track-progress [audioTrack]="track"></audio-track-progress>
          <audio-track-progress-bar dark duration progress [audioTrack]="audio"></audio-track-progress-bar>-->
          <!--<em style="font-size:.5em">Track ID: {{audio.id}}</em>-->
        </div>
        <ion-icon name="add" color="header" (click)="addToQueue(track)" item-right></ion-icon>
      </ion-item>
    </audio-track>
```

**Comment by arielfaur** [comment]
@ehusaint This is weird because the code that creates the binding is in the page constructor so that should execute only once. You could try moving that block to the `ionViewDidLoad` method but I don't know if that will make a change.

**Comment by andrewlongdotcom** [comment]
i think i am facing a similar issue in a podcast app i am building. similar to @ehusaint scenario i may do the following:

1. navigate to a podcast page which contains the audio-track component
2. press play
3. navigate to some other pages
4. come back to the original podcast page and i would like to have the audio-track component still showing correctly the playing status and track progress

i thought what i might be able to do is have 2 separate audio-track components on the page. one would be displayed when navigating to a podcast which is not currently being played and another to be displayed when i navigate back to the podcast that is currently being played.

for the component that would bind to the currently playing track i am trying to do the following in my page constructor to pull the track back from the AudioProvider and bind it to the audio-track component:

`var current = this._sharedDataService.getAudioProvider().current;

      if (current !== undefined &&
          current !== null &&
          this._sharedDataService.getAudioProvider().tracks !== undefined && 
          this._sharedDataService.getAudioProvider().tracks !== null &&
          this._sharedDataService.getAudioProvider().tracks.length > 0 &&
          this._sharedDataService.getAudioProvider().tracks[current].isPlaying &&
          this._sharedDataService.getAudioProvider().tracks[current].src === this.selectedFeedItem.link) {
            this.isCurrentPlayingTrack = true;            
            var track = this._sharedDataService.getAudioProvider().tracks[current];
            this.existingTrack = track;
            var tracks = this._sharedDataService.getAudioProvider().tracks;
            this.playing = true;
      }`

however, this doesn't work and i end up with the following error:
`Error: Uncaught (in promise): TypeError: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at AudioTrackComponent.ngOnInit (http://localhost:8100/build/main.js:62899:20)
    at checkAndUpdateDirectiveInline (http://localhost:8100/build/main.js:11112:19)
    at checkAndUpdateNodeInline (http://localhost:8100/build/main.js:12490:17)
    at checkAndUpdateNode (http://localhost:8100/build/main.js:12458:16)
    at debugCheckAndUpdateNode (http://localhost:8100/build/main.js:13087:59)
    at debugCheckDirectivesFn (http://localhost:8100/build/main.js:13028:13)
    at Object.eval [as updateDirectives] (ng:///AppModule/PodcastPlayItem.ngfactory.js:542:5)
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:8100/build/main.js:13013:21)
    at checkAndUpdateView (http://localhost:8100/build/main.js:12425:14)
    at callViewAction (http://localhost:8100/build/main.js:12740:17)
    at execEmbeddedViewsAction (http://localhost:8100/build/main.js:12712:17)
    at checkAndUpdateView (http://localhost:8100/build/main.js:12426:5)
    at callViewAction (http://localhost:8100/build/main.js:12740:17)
    at execComponentViewsAction (http://localhost:8100/build/main.js:12686:13)
    at g (http://localhost:8100/build/polyfills.js:3:7133)
    at l (http://localhost:8100/build/polyfills.js:3:6251)
    at http://localhost:8100/build/polyfills.js:3:6805
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15213)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:4489:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15134)
    at n.runTask (http://localhost:8100/build/polyfills.js:3:10390)
    at a (http://localhost:8100/build/polyfills.js:3:5313)
    at HTMLButtonElement.invoke (http://localhost:8100/build/polyfills.js:3:16210)`

I don't really know at this point if this is even a viable option for what i am trying to accomplish or not

**Comment by andrewlongdotcom** [comment]
so just to follow up on my issue, it seems my approach was viable, but when i re-navigate to the page for an podcast that is the current item, i had to remove the audio-track component. i just bind the existing track that i retrieve in my page constructor to an audio-track-progress-bar

**Comment by arielfaur** [comment]
Could any of you maybe provide a link to a project to download and test this scenario?

**Comment by chalosalvador** [comment]
Hi, maybe you guys already found a solution to this but I want to post it here anyways. Thanks to Dzejms in #112 I found a solution. I added these lines to the constructor of my page component and the tracks list is being reseted. Hope it helps.

`// RESET THE ARRAY OF TRACKS
    if (this._audioProvider.tracks.length !== 0) {
      this._audioProvider.tracks[0].destroy();
      this._audioProvider.tracks.splice(0);
    }`

**Comment by ehusaint** [comment]
@chalosalvador - Thanks for the update but it seems like my issue was different. My scenario:

1. Go to homepage. 
2. Navigate to Album A (has 4 tracks)
3. constructor creates the id for all the track on this page and adds to the allTracks list. 
4. Navigate back to home page. 
5. Again click Album A (has same 4 tracks)
6. Construcutor creates the new id for all the track on this same page. So now I have 8 tracks in allTrack list. 

I had to avoid that.

**Comment by chalosalvador** [comment]
yeah, that looks exactly like my issue and adding those lines solved it. As far as I understand the `allTracks` variable is populated from the `this._audioProvider.tracks` property.

**Comment by ehusaint** [comment]
I'm not sure how that code would solve the problem. So you are saying that in the step "5" above, those 4 new tracks will not be created if I have this code? @chalosalvador

**Comment by hvlads** [comment]
I had the same problem and it helped me:

` createAlbumPlayList(tracks) {
    this.myTracks = [];
    for (let i = 0; i < tracks.length; i++) {
      let id = tracks[i]['id'];
      let s = tracks[i]['file'];
      let n = tracks[i]['name'];
     ..........

**let src2 = this._audioProvider.tracks.map(function (e) {
        return e.src;
      }).indexOf(s);
      let track;
      if (src2 != -1) {
        track = this._audioProvider.tracks[src2];
      } else {
        track =
          {
            id: id,
            title:n,
            src: s,
            artist: artist,
            art: art,
            preload: 'metadata'
          };
      }**
      this.myTracks.push(track);
      ....
  return this.myTracks;
`

**Comment by fdambrosio** [comment]
Hi, I'm trying to use 
`destroy()`
and 
`stop()`
with a mp3 live streaming file. 

In both case the audio stops  to play, but the browser continues to download the file/track buffering it. How can I stop that file download?

**Comment by arielfaur** [comment]
Hey there!
I just uploaded version `3.2.0` with some new features and examples such as basic playlist management. It would be great to get some feedback. Hopefully this one solves some of the issues you reported.
Here's the link to the demo of the new version with playlist management:
https://arielfaur.github.io/ionic-audio-demo/

**Comment by 95deepan** [comment]
Hi @arielfaur , Can you please share the source code of the above demo ? Because I am getting too many errors regarding HTML. It says <audio-track> and <audio-progress-bar> element cannot be parsed- Unknown element, like that. Please anyone upload some working code..

**Comment by 95deepan** [comment]
I got this error in my console:

```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'track' since it isn't a known property of 'audio-track'.
1. If 'audio-track' is an Angular component and it has 'track' input, then verify that it is part of this module.
2. If 'audio-track' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

  <ion-list>
    <audio-track #audio *ngFor="let track of myTracks"  [ERROR ->][track]="track" (onFinish)="onTrackFinished($event)">
      <ion-item>  
        <ion-thumbnail item-"): ng:///DailyDevotionPageModule/DailyDevotionPage.html@27:56
Can't bind to 'audioTrack' since it isn't a known property of 'audio-track-play'.
1. If 'audio-track-play' is an Angular component and it has 'audioTrack' input, then verify that it is part of this module.
2. If 'audio-track-play' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("     <ion-thumbnail item-left>
          <img src="{{audio.art}}">
          <audio-track-play dark [ERROR ->][audioTrack]="audio"><ion-spinner></ion-spinner></audio-track-play>  
        </ion-thumbnail>
      "): ng:///DailyDevotionPageModule/DailyDevotionPage.html@31:33
'audio-track-play' is not a known element:
1. If 'audio-track-play' is an Angular component, then verify that it is part of this module.
2. If 'audio-track-play' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        <ion-thumbnail item-left>
          <img src="{{audio.art}}">
          [ERROR ->]<audio-track-play dark [audioTrack]="audio"><ion-spinner></ion-spinner></audio-track-play>  
        "): ng:///DailyDevotionPageModule/DailyDevotionPage.html@31:10
Can't bind to 'audioTrack' since it isn't a known property of 'audio-track-progress-bar'.
1. If 'audio-track-progress-bar' is an Angular component and it has 'audioTrack' input, then verify that it is part of this module.
2. If 'audio-track-progress-bar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("/strong> ⚬ <em>{{audio.artist}}</em></p>
          <audio-track-progress-bar dark duration progress [ERROR ->][audioTrack]="audio" [ngStyle]="{visibility: audio.completed > 0 ? 'visible' : 'hidden'}"></audio-tra"): ng:///DailyDevotionPageModule/DailyDevotionPage.html@35:59
'audio-track-progress-bar' is not a known element:
1. If 'audio-track-progress-bar' is an Angular component, then verify that it is part of this module.
2. If 'audio-track-progress-bar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("idth:100%">
          <p><strong>{{audio.title}}</strong> ⚬ <em>{{audio.artist}}</em></p>
          [ERROR ->]<audio-track-progress-bar dark duration progress [audioTrack]="audio" [ngStyle]="{visibility: audio.c"): ng:///DailyDevotionPageModule/DailyDevotionPage.html@35:10
'audio-track' is not a known element:
1. If 'audio-track' is an Angular component, then verify that it is part of this module.
2. If 'audio-track' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("

  <ion-list>
    [ERROR ->]<audio-track #audio *ngFor="let track of myTracks"  [track]="track" (onFinish)="onTrackFinished($even"): ng:///DailyDevotionPageModule/DailyDevotionPage.html@27:4
Error: Template parse errors:
Can't bind to 'track' since it isn't a known property of 'audio-track'.
1. If 'audio-track' is an Angular component and it has 'track' input, then verify that it is part of this module.
2. If 'audio-track' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

  <ion-list>
    <audio-track #audio *ngFor="let track of myTracks"  [ERROR ->][track]="track" (onFinish)="onTrackFinished($event)">
      <ion-item>  
        <ion-thumbnail item-"): ng:///DailyDevotionPageModule/DailyDevotionPage.html@27:56
Can't bind to 'audioTrack' since it isn't a known property of 'audio-track-play'.
1. If 'audio-track-play' is an Angular component and it has 'audioTrack' input, then verify that it is part of this module.
2. If 'audio-track-play' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("     <ion-thumbnail item-left>
          <img src="{{audio.art}}">
          <audio-track-play dark [ERROR ->][audioTrack]="audio"><ion-spinner></ion-spinner></audio-track-play>  
        </ion-thumbnail>
      "): ng:///DailyDevotionPageModule/DailyDevotionPage.html@31:33
'audio-track-play' is not a known element:
1. If 'audio-track-play' is an Angular component, then verify that it is part of this module.
2. If 'audio-track-play' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        <ion-thumbnail item-left>
          <img src="{{audio.art}}">
          [ERROR ->]<audio-track-play dark [audioTrack]="audio"><ion-spinner></ion-spinner></audio-track-play>  
        "): ng:///DailyDevotionPageModule/DailyDevotionPage.html@31:10
Can't bind to 'audioTrack' since it isn't a known property of 'audio-track-progress-bar'.
1. If 'audio-track-progress-bar' is an Angular component and it has 'audioTrack' input, then verify that it is part of this module.
2. If 'audio-track-progress-bar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("/strong> ⚬ <em>{{audio.artist}}</em></p>
          <audio-track-progress-bar dark duration progress [ERROR ->][audioTrack]="audio" [ngStyle]="{visibility: audio.completed > 0 ? 'visible' : 'hidden'}"></audio-tra"): ng:///DailyDevotionPageModule/DailyDevotionPage.html@35:59
'audio-track-progress-bar' is not a known element:
1. If 'audio-track-progress-bar' is an Angular component, then verify that it is part of this module.
2. If 'audio-track-progress-bar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("idth:100%">
          <p><strong>{{audio.title}}</strong> ⚬ <em>{{audio.artist}}</em></p>
          [ERROR ->]<audio-track-progress-bar dark duration progress [audioTrack]="audio" [ngStyle]="{visibility: audio.c"): ng:///DailyDevotionPageModule/DailyDevotionPage.html@35:10
'audio-track' is not a known element:
1. If 'audio-track' is an Angular component, then verify that it is part of this module.
2. If 'audio-track' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("

  <ion-list>
    [ERROR ->]<audio-track #audio *ngFor="let track of myTracks"  [track]="track" (onFinish)="onTrackFinished($even"): ng:///DailyDevotionPageModule/DailyDevotionPage.html@27:4
    at syntaxError (compiler.es5.js:1540)
    at TemplateParser.parse (compiler.es5.js:12031)
    at JitCompiler._compileTemplate (compiler.es5.js:25782)
    at compiler.es5.js:25706
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.es5.js:25706)
    at createResult (compiler.es5.js:25591)
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.es5.js:4149)
    at t.invoke (polyfills.js:3)
    at syntaxError (compiler.es5.js:1540)
    at TemplateParser.parse (compiler.es5.js:12031)
    at JitCompiler._compileTemplate (compiler.es5.js:25782)
    at compiler.es5.js:25706
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.es5.js:25706)
    at createResult (compiler.es5.js:25591)
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.es5.js:4149)
    at t.invoke (polyfills.js:3)
    at c (polyfills.js:3)
    at Object.reject (polyfills.js:3)
    at NavControllerBase._fireError (nav-controller-base.js:321)
    at NavControllerBase._failed (nav-controller-base.js:309)
    at nav-controller-base.js:364
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.es5.js:4149)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
defaultErrorLogger @ core.es5.js:1084
```

**Comment by 95deepan** [comment]
If we use lazy-loading in ionic ^3.0.  then it emits lot of errors. Please fix @arielfaur
