### ISSUE TITLE
Unhandled Promise rejection: Template parse errors: Can't bind to 'track' since it isn't a known property of 'audio-track'.

### ISSUE THREAD

**Issue by drhouse7** [arielfaur/ionic-audio#129]
Hi,
I'm new at Angular and Ionic...I tried this plugin but still get this message:

```
Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'audioTrack' since it isn't a known property of 'ion-item'.
1. If 'ion-item' is an Angular component and it has 'audioTrack' input, then verify that it is part of this module.
2. If 'ion-item' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

  <audio-track #track [track]="singleTrack">
    <ion-item [ERROR ->][audioTrack]="track">
      <ion-thumbnail item-left>
        <img src="{{track.art}}">
"): ng:///AboutModule/AboutComponent.html@33:14
Error: Template parse errors:
Can't bind to 'audioTrack' since it isn't a known property of 'ion-item'.
1. If 'ion-item' is an Angular component and it has 'audioTrack' input, then verify that it is part of this module.
2. If 'ion-item' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

  <audio-track #track [track]="singleTrack">
    <ion-item [ERROR ->][audioTrack]="track">
      <ion-thumbnail item-left>
        <img src="{{track.art}}">
"): ng:///AboutModule/AboutComponent.html@33:14
    at syntaxError (http://localhost:8100/build/main.js:105019:34)
    at TemplateParser.parse (http://localhost:8100/build/main.js:115510:19)
    at JitCompiler._compileTemplate (http://localhost:8100/build/main.js:129261:39)
    at http://localhost:8100/build/main.js:129185:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:8100/build/main.js:129185:19)
    at createResult (http://localhost:8100/build/main.js:129070:19)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:8971)
    at r.run (http://localhost:8100/build/polyfills.js:3:4140)
    at http://localhost:8100/build/polyfills.js:3:13731
    at syntaxError (http://localhost:8100/build/main.js:105019:34)
    at TemplateParser.parse (http://localhost:8100/build/main.js:115510:19)
    at JitCompiler._compileTemplate (http://localhost:8100/build/main.js:129261:39)
    at http://localhost:8100/build/main.js:129185:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:8100/build/main.js:129185:19)
    at createResult (http://localhost:8100/build/main.js:129070:19)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:8971)
    at r.run (http://localhost:8100/build/polyfills.js:3:4140)
    at http://localhost:8100/build/polyfills.js:3:13731
    at c (http://localhost:8100/build/polyfills.js:3:13190)
    at c (http://localhost:8100/build/polyfills.js:3:12876)
    at http://localhost:8100/build/polyfills.js:3:13722
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9655)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:4831)
    at o (http://localhost:8100/build/polyfills.js:3:1891)
    at <anonymous>
n.onUnhandledError @ VM74 polyfills.js:3
r @ VM74 polyfills.js:3
(anonymous) @ VM74 polyfills.js:3
n.microtaskDrainDone @ VM74 polyfills.js:3
o @ VM74 polyfills.js:3
```
I did everything you wrote [here](http://arielfaur.github.io/ionic-audio/2.0/index.html)

Also on my text editor, I get this error
`Property 'selectedTrack' does not exists on type`

Any support is really appreciate, thanks!

**Comment by drhouse7** [comment]
First of all I saw the demo here that is completely different from this http://arielfaur.github.io/ionic-audio/2.0/index.html and I change it accordingly on my project...after
I edit my component page adding **NO_ERRORS_SCHEMA** likes below:

```
import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SharedModule } from '../../app/shared/shared.module';
import { AboutComponent } from './about-component/about.component';

@NgModule({
  declarations: [
    AboutComponent
  ],
  imports: [
  	CommonModule,
  	SharedModule
  ],
  exports: [
    AboutComponent
  ],
  entryComponents:[
  	AboutComponent
  ],
  schemas: [ NO_ERRORS_SCHEMA ]
})
export class AboutModule {}
```

Now all errors are gone and it works.
