### ISSUE TITLE
Cannot inject AudioProvider into App Component (Cannot instantiate cyclic dependency) since 3.1.0

### ISSUE THREAD

**Issue by tbergeron** [arielfaur/ionic-audio#137]
I've been bashing my head for almost a week now and I found that since 3.1.0's change that we need to pass `MyApp` to `IonicAudioModule.forRoot();` i.e. `IonicAudioModule.forRoot(MyApp);`

It causes an error below in the browser console. As soon as I remove the AudioProvider line from the construct it goes away.

```
// ...
import { Component } from '@angular/core';
import { Platform, Events, LoadingController } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
import { SignInPage } from '../pages/sign-in/sign-in';
import { AudioProvider } from 'ionic-audio';

export class MyApp {
  rootPage: any = SignInPage;

  constructor(
    platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen,
    public events: Events, public loadingCtrl: LoadingController,
    public audioProvider: AudioProvider // Remove this and the error goes away
  ) {
// ...
```

Here's the error message:

```
polyfills.js:3 Unhandled Promise rejection: Provider parse errors:
Cannot instantiate cyclic dependency! AudioProvider ("[ERROR ->]"): in NgModule AppModule in ./AppModule@-1:-1 ; Zone: <root> ; Task: Promise.then ; Value: Error: Provider parse errors:
Cannot instantiate cyclic dependency! AudioProvider ("[ERROR ->]"): in NgModule AppModule in ./AppModule@-1:-1
    at NgModuleProviderAnalyzer.parse (vendor.js:94333)
    at NgModuleCompiler.compile (vendor.js:100806)
    at JitCompiler._compileModule (vendor.js:109064)
    at createResult (vendor.js:109004)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3) Error: Provider parse errors:
Cannot instantiate cyclic dependency! AudioProvider ("[ERROR ->]"): in NgModule AppModule in ./AppModule@-1:-1
    at NgModuleProviderAnalyzer.parse (http://localhost:8100/build/vendor.js:94333:19)
    at NgModuleCompiler.compile (http://localhost:8100/build/vendor.js:100806:24)
    at JitCompiler._compileModule (http://localhost:8100/build/vendor.js:109064:73)
    at createResult (http://localhost:8100/build/vendor.js:109004:26)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:8971)
    at r.run (http://localhost:8100/build/polyfills.js:3:4140)
    at http://localhost:8100/build/polyfills.js:3:13731
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9655)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:4831)
    at o (http://localhost:8100/build/polyfills.js:3:1891)
n.onUnhandledError @ polyfills.js:3
polyfills.js:3 Error: Uncaught (in promise): Error: Provider parse errors:
Cannot instantiate cyclic dependency! AudioProvider ("[ERROR ->]"): in NgModule AppModule in ./AppModule@-1:-1
Error: Provider parse errors:
Cannot instantiate cyclic dependency! AudioProvider ("[ERROR ->]"): in NgModule AppModule in ./AppModule@-1:-1
    at NgModuleProviderAnalyzer.parse (vendor.js:94333)
    at NgModuleCompiler.compile (vendor.js:100806)
    at JitCompiler._compileModule (vendor.js:109064)
    at createResult (vendor.js:109004)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at NgModuleProviderAnalyzer.parse (vendor.js:94333)
    at NgModuleCompiler.compile (vendor.js:100806)
    at JitCompiler._compileModule (vendor.js:109064)
    at createResult (vendor.js:109004)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at c (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at <anonymous>
n.onUnhandledError @ polyfills.js:3
```

Rollbacking to 3.0.0 fixes the error.

**Comment by arielfaur** [comment]
@tbergeron `IonicAudioModule.forRoot()` expects a factory function as a parameter. There is a defult one provided with the module, or you can write a custom one.

```
import { IonicAudioModule, WebAudioProvider, CordovaMediaProvider, defaultAudioProviderFactory } from 'ionic-audio';

/**
 * Sample custom factory function to use with ionic-audio
 */
export function myCustomAudioProviderFactory() {
  return (window.hasOwnProperty('cordova')) ? new CordovaMediaProvider() : new WebAudioProvider();
}

@NgModule({
  declarations: declarations(),
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
    IonicAudioModule.forRoot(defaultAudioProviderFactory), 
    // or use a custom provided function shown above myCustomAudioProviderFactory
  ],

```

**Comment by tbergeron** [comment]
Thanks for the response, I had this on hold but I'm so happy you helped me figure it out!
