### ISSUE TITLE
This code is not working for me.

### ISSUE THREAD

**Issue by bankim** [arielfaur/ionic-audio#32]
Hi, this code code is not working for me.

**Comment by leonardosalles** [comment]
You need to be more specific buddy, what kind of error do you get? When you say that the code is not working to you and not specify any additional data it is white trash.

**Comment by bankim** [comment]
Please see the log here. And if you can help me on that.

sudo ionic platform add ios
Error: %s Error: ENOENT, no such file or directory '/Users/bankimdebnath/Downloads/ionic-audio-master/hooks'
    at Error (native)
    at Object.fs.readdirSync (fs.js:761:18)
    at Object.setHooksPermission (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/hooks.js:116:24)
    at Object.IonicTask.run (/usr/local/lib/node_modules/ionic/lib/ionic/cordova.js:51:13)
    at Object.run (/usr/local/lib/node_modules/ionic/lib/cli.js:95:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/bin/ionic:9:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
Updated the hooks directory to have execute permissions
Error happened { [Error: ENOENT, open '/Users/bankimdebnath/Downloads/ionic-audio-master/config.xml']
  errno: -2,
  code: 'ENOENT',
  path: '/Users/bankimdebnath/Downloads/ionic-audio-master/config.xml' }
Error: ENOENT, open '/Users/bankimdebnath/Downloads/ionic-audio-master/config.xml'
    at Error (native)

Thanks.

**Comment by bankim** [comment]
after download the file I am not getting hooks folder and config.xml file. can you update it up and run standards ??

**Comment by arielfaur** [comment]
You don't need to use sudo to add the platform. It seems you have some permission issues.

**Comment by leonardosalles** [comment]
Yeah, try to run the command without sudo, if it not work try to change the chmod/permissions of your project folder

**Comment by bankim** [comment]
yes now it is running on simulator. but i am seeing anything there. it is a blank screen.

**Comment by arielfaur** [comment]
You should check the device console (using remote debugging) to see if there are any errors
