### ISSUE TITLE
Not ready for Ionic 2 final?

### ISSUE THREAD

**Issue by pascalgermain** [arielfaur/ionic-audio#89]
Hi, I built an app with Ionic 2 (RC3) and the great ionic-audio, and Ionic 2 final just released :)

It seems that ionic-audio is not compatible with this final version (I remember I had the same problem when trying to Ionic 2 RC4). Would be wonderful if it could fit the final version :) (and the docs could reflect it too).

Here's what I get :

> Runtime Error
Error in ./AudioPlayerComponent class AudioPlayerComponent - caused by: Cannot read property 'isImgsUpdatable' of null

> Stack
TypeError: Cannot read property 'isImgsUpdatable' of null
    at Img.update (http://localhost:8100/build/main.js:60904:39)
    at Img.set [as src] (http://localhost:8100/build/main.js:60874:22)
    at Wrapper_Img.check_src (/IonicModule/Img/wrapper.ngfactory.js:25:22)
    at View_AudioPlayerComponent2.detectChangesInternal (/AppModule/AudioPlayerComponent/component.ngfactory.js:313:17)
    at View_AudioPlayerComponent2.AppView.detectChanges (http://localhost:8100/build/main.js:99083:14)
    at View_AudioPlayerComponent2.DebugAppView.detectChanges (http://localhost:8100/build/main.js:99176:44)
    at ViewContainer.detectChangesInNestedViews (http://localhost:8100/build/main.js:99268:37)
    at View_AudioPlayerComponent1.detectChangesInternal (/AppModule/AudioPlayerComponent/component.ngfactory.js:121:14)
    at View_AudioPlayerComponent1.AppView.detectChanges (http://localhost:8100/build/main.js:99083:14)
    at View_AudioPlayerComponent1.DebugAppView.detectChanges (http://localhost:8100/build/main.js:99176:44)

> Ionic Framework: 2.0.0
Ionic Native: 2.4.1
Ionic App Scripts: 1.0.0
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 7.4.0
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

Thanks !
(if interested, the app is available at [http://app.captainweb.net/](http://app.captainweb.net/))

**Comment by arielfaur** [comment]
You are right. I haven't had the time to upgrade yet 😞

**Comment by arielfaur** [comment]
It's done. Upgraded to Ionic 2 final. There are a few changes related to the setup, please check the updated docs:
http://arielfaur.github.io/ionic-audio/2.0/index.html

**Comment by pascalgermain** [comment]
Amazing!!! Thanks a lot man, cheers!
